# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0025aa6b6b73036e2b2501a28bf9925e859d09c158bcd6d6f1d227bc34f51fba5379d97b33ceffa229ec49ad1cc20a85686af0b5bef7139d56ab8ba462f8c82

test:
  secret_key_base: ff964b563908d7b3d906625f6e3551518c37a140122e92f92605e11e04926596feb9075fe505e1aa440ce663a62d6bac7fd5af64cc429d981b8ba20a5551cf9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
